# values.yaml

# Application configuration
application:
  name: my-app
  image:
    repository: my-container-registry/my-app
    tag: latest
  replicaCount: 3
  port: 8080
  env:
    - name: ENV_VAR1
      value: value1
    - name: ENV_VAR2
      value: value2

# Kubernetes configuration
kubernetes:
  namespace: default
  service:
    type: ClusterIP | NodePort | LoadBalancer | ExternalName
    name: my-app-service
  ingress:
    enabled: true | false
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: myapp.example.com
        paths:
          - /

# Resources configuration
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

# Persistence configuration
persistence:
  enabled: true | false
  storageClass: standard
  accessMode: ReadWriteOnce | ReadWriteMany | ReadOnlyMany
  size: 1Gi

# Pull policy
imagePullPolicy: IfNotPresent | Always | Never
