version: "3"
services:
  mongodb:
    image: mongo
    networks:
      - my-network

  my-app:
    image: dipeshsingh253/docker-learnings:my-app
    ports:
      - 8080:8080
    networks:
      - my-network
    depends_on:
      - mongodb

networks:
  my-network:
    driver: bridge
