apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: dipeshsingh253/docker-images:version-2.0.0
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_HOST
              value: mongodb-container
