server:
  port: 8088

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
  application:
    name: product-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka # basic auth in eureka


management:
  zipking:
    tracing:
      endpoint: http://localhost:9411
  tracing:
    sampling:
      probability: 1.0