version: "3.8"
services:
  jwtapp:
    build: .
    ports:
      - 8888:8080
    container_name: springsecurityjwt
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
#    depends_on:
#      - mysqldb
    restart: always


  db:
    image: "mysql:8.0"
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test


    ports:
        - 3307:3306
    volumes:
      - F:\DB\mysql\:/var/lib/mysql

