version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    networks:
      - my-network

  my-app:
    image: dipeshsingh253/docker-images:version-2.0.0
    container_name: spring-service-container
    ports:
      - 8080:8080
    networks:
      - my-network
    depends_on:
      - mongodb

networks:
  my-network:
    driver: bridge
