server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory-service
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
  application:
    name: inventory-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka # basic auth in eureka


management:
  zipking:
    tracing:
      endpoint: http://localhost:9411
  tracing:
    sampling:
      probability: 1.0